### ISSUE TITLE
Parou de funcionar.

### ISSUE THREAD

**Issue by esteves023** [elvisvasc/whatsapp-audio-speed-changer#1]
A extensão parou de funcionar por volta do dia 09/04. Áudio está picotando e não acelera. Deve ser alguma atualização do site whatsapp web

**Comment by DrBlort** [comment]
I can confirm that all audio elements playbackRate is being set to 1 constantly when they start playing, although I don't know enough to identify exactly where in whatsapp code

**Comment by elvisvasc** [comment]
Hi,
Unfortunately this extension is no longer able to function properly. Whatsapp web now serves audios via stream and it is not possible to accelerate them.
Sorry guys :(

**Comment by elvisvasc** [comment]
Closing this topic.
